### PR TITLE
load securityHandlers from sails api/swagger/securityHandlers.js

### PR DESCRIPTION
**Pull request by cgalibern**
```
Example of sails swagger security file: api/swagger/securityHandlers.js

  module.exports.securityHandlers = {
    mybasic:function securityHandler1(req, authOrSecDef, scopesOrApiKey, cb) {
        // your security code
        cb();
        },
  };

Extract of api/swagger/swagger.yaml
...
securityDefinitions:
  mybasic:
     type: basic
paths:
  /hello:
     # binds a127 app logic to a route
     x-swagger-router-controller: hello_world
     get:
       security:
         - mybasic: []
...
```

### CODE REVIEW

**Comment by cgalibern** [comment]
@theganyo, not sure this is the way to do, but this fix allow definitions of custom swaggerSecurityHandlers into sails config file: api/swagger/securityHandlers.js.
it follow initial idea from @molexx, but test its presence.

This may help into issue #1

**Comment by theganyo** [comment]
@cgalibern This is interesting, thanks. Is the reason for this just to avoid defining the security handler in your app.js or do is there additional motivation for it? I'm just wondering as maybe it's a strategy that I should apply more broadly. Thanks.

**Comment by cgalibern** [comment]
@theganyo I have tried define it into <swagger-sails-project>/app.js but it failed.
Perhaps it is only available on swagger express projects or I have missed something ?

**Comment by cgalibern** [comment]
I have also tried to keep app.js unchanged all updates goes to api/ and config/

**Comment by theganyo** [comment]
I'm not sure what version of swagger-sails you're using at present, but the latest version should definitely work with security handlers and I do have tests around it... so if it's not working for you, it certainly needs to be addressed. (But note that if you're using a version of swagger-sails prior to 0.6.0 and want to update, you'll need to make a couple of small changes. See: https://github.com/theganyo/swagger-node-runner/releases).

That said, I do like your thought of the system loading security handlers from a directory automatically without app.js changes. I think directory (and possibly file) should be configurable, but probably it should be loaded from the api/helpers/securityHandlers.js by default. What do you think?

**Comment by cgalibern** [comment]
I have updated the pull request having file loaded from api/helpers/securityHandlers.js.

Perhaps I have missed something about how to declare securityHandlers into app.js.
Can you provide a sails app.js example where securityHandlers are defined ?

here is my app.js contents:

``` javascript
 process.chdir(__dirname);

// Ensure a "sails" can be located:
(function() {
  var sails;
  try {
    sails = require('sails');
  } catch (e) {
    console.error('To run an app using `node app.js`, you usually need to have a version of `sails` installed in the same directory as your app.');
    console.error('To do that, run `npm install sails`');
    console.error('');
    console.error('Alternatively, if you have sails installed globally (i.e. you did `npm install -g sails`), you can use `sails lift`.');
    console.error('When you run `sails lift`, your app will still use a local `./node_modules/sails` dependency if it exists,');
    console.error('but if it doesn\'t, the app will run with the global sails instead!');
    return;
  }

  // Try to get `rc` dependency
  var rc;
  try {
    rc = require('rc');
  } catch (e0) {
    try {
      rc = require('sails/node_modules/rc');
    } catch (e1) {
      console.error('Could not find dependency: `rc`.');
      console.error('Your `.sailsrc` file(s) will be ignored.');
      console.error('To resolve this, run:');
      console.error('npm install rc --save');
      rc = function () { return {}; };
    }
  }


  // Start server
  sails.lift(rc('sails'));

})();
```

**Comment by cgalibern** [comment]
@theganyo I have reverted location to api/swagger/securityHandlers since api/helpers/ dir doesn't exists in sails default api dirs.

**Comment by theganyo** [comment]
@cgalibern 

Thanks for all your ideas. I've just checked in a solution that is fully configurable for whatever path you'd like and should work for all providers including Sails. Can you take a look at this and tell me what you think? You'd just configure the module path to load the handlers from as "securityHandlersModule" in the config for the swagger_security fitting like so:

``` yaml
    _swagger_security:
      name: swagger_security
      securityHandlersModule: api/helpers/securityHandlers

    # pipe for all swagger-node controllers
    swagger_controllers:
      - onError: json_error_handler
      - cors
      - swagger_params_parser
      - _swagger_security
      - _swagger_validate
      - express_compatibility
      - _router
```

Then, you'd just write your module (eg. api/helpers/securityHandlers.js) like so:

``` javascript
  module.exports = {
    one_way: function securityHandler1(req, authOrSecDef, scopesOrApiKey, cb) {
        cb();
    },
    or_another: function securityHandler2(req, res, next) {
        next();
    }
  };
```

See: https://github.com/theganyo/swagger-node-runner/blob/master/fittings/swagger_security.js#L15.

**Comment by cgalibern** [comment]
@theganyo I did add example here https://github.com/cgalibern/swagger-sails-basicauth-example, before seeing your last update.
I will try your last idea

**Comment by cgalibern** [comment]
@theganyo great !!  your last update also fix it in a better way.
Thanks a lot

Will you release a new update soon ?

**Comment by theganyo** [comment]
Thanks! Yes, I'll look at releasing it tomorrow. I'll let you know.

**Comment by cgalibern** [comment]
@theganyo will it be also possible to update https://github.com/swagger-api/swagger-node/blob/master/project-skeletons/sails/package.json
to use a more recent swagger-sails-hook:

``` javascript
from  "swagger-sails-hook": "^0.1.0"
to    "swagger-sails-hook": "^0.6.0"
```

I ran into some issues that are resolved now (example can't set headers after they are sent)

**Comment by theganyo** [comment]
This has been published as swagger-node-runner@0.6.10. It will be automatically picked up if you are using the latest swagger-sails-hook (0.6.1) and reinstall your project dependencies. See the release notes here: https://github.com/theganyo/swagger-node-runner/releases/tag/v0.6.10. Please let me know if you run into any issues.

I'm not changing the swagger_node templates quite yet, but I will be soon.

**Comment by cgalibern** [comment]
@theganyo Thanks,
I ran into another issue when call back fails and calls `next(new Error('access denied!'));`
It send tries to send a second 200 Ok response even if it as already send a 403
So we get a Error: Can't set headers after they are sent...

``` javascript
swagger:swagger_security exec +3ms
swagger:swagger_security Security check (basicAuthAtDomainUk): denied +3ms
swagger:swagger_security Request allowed: false +1ms
swagger:json_error_handler exec: access denied! +2ms
swagger:content setting response headers: {"Content-Type":"application/json"} +1ms
swagger:content sending response body: {"message":"access denied!","code":"server_error","statusCode":403} +0ms
_http_outgoing.js:338
    throw new Error('Can\'t set headers after they are sent.');
    ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:338:11)
    at ServerResponse.res.setHeader (/somewhere/node_modules/sails/node_modules/connect/lib/patch.js:133:22)
    at ServerResponse.res.set.res.header (/somewhere/node_modules/sails/node_modules/express/lib/response.js:577:10)
    at ServerResponse.res.send (/somewhere/node_modules/sails/node_modules/express/lib/response.js:142:12)
    at ServerResponse.res.json (/somewhere/node_modules/sails/node_modules/express/lib/response.js:223:15)
    at ServerResponse.jsonx (/somewhere/node_modules/sails/lib/hooks/responses/index.js:218:21)
    at Object.sendOK (/somewhere/api/responses/ok.js:28:16)
    at ServerResponse.bound [as ok] (/somewhere/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at found (/somewhere/node_modules/sails/lib/hooks/blueprints/actions/find.js:61:9)
    at wrapper (/somewhere/node_modules/sails/node_modules/waterline/node_modules/lodash/index.js:3602:19)
    at applyInOriginalCtx (/somewhere/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/somewhere/node_modules/sails/node_modules/waterline/lib/waterline/utils/normalize.js:320:18)
    at callback.success (/somewhere/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/normalize.js:33:31)
    at _switch (/somewhere/node_modules/sails/node_modules/waterline/node_modules/switchback/lib/factory.js:48:28)
    at returnResults (/somewhere/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/basic.js:392:9)
    at /somewhere/node_modules/sails/node_modules/waterline/lib/waterline/query/finders/basic.js:277:16
```

**Comment by theganyo** [comment]
@cgalibern I'm not seeing that. Is there a way you can share a sample that recreates it?

**Comment by cgalibern** [comment]
I will try to reproduce an example

**Comment by cgalibern** [comment]
@theganyo I have pushed an example of failure:
`git clone https://github.com/cgalibern/show-issue.git && cd show-issue && npm install && DEBUG="swagger:*" swagger project start`

correct calls are:
-  curl -i http://localhost:10010/hello -u john:john-uk-password
-  curl -i http://localhost:10010/person -u john:john-uk-password
-  curl -i http://localhost:10010/hello -u john:ABADPASSWORD

Failure is here:
-  curl -i http://localhost:10010/person -u john:ABADPASSWORD

I don't understand why it occur on PersonController and not on hello_world

**Comment by theganyo** [comment]
Based on the error, it looks like it's somehow related to Waterline. Also, based on output from using DEBUG=*, I see the following from /hello:

```
  pipes:content output (context[output]): "{\"message\":\"{\\\"message\\\":\\\"user password not valid in UK\\\",\\\"code\\\":\\\"server_error\\\",\\\"statusCode\\\":403}\"}" +0ms
  swagger setting response statusCode: 403 +0ms
  swagger:content setting response headers: {"Content-Type":"application/json"} +0ms
  swagger:content sending response body: {"message":"{\"message\":\"user password not valid in UK\",\"code\":\"server_error\",\"statusCode\":403}"} +1ms
  express-session saving +22ms
  express-session set-cookie sails.sid=s%3AnRcpH0HAzhgry_SnXAewQhwrlAo6hXUk.2PXJoTpSKC6OoXxy%2Bze43enN%2FRfudraR%2FZ3zWUarl1A; Path=/; HttpOnly +2ms
  connect:dispatcher serveStatic  : /hello +1ms
```

And this from /person:

```
  pipes:content output (context[output]): "{\"message\":\"{\\\"message\\\":\\\"user password not valid in UK\\\",\\\"code\\\":\\\"server_error\\\",\\\"statusCode\\\":403}\"}" +0ms
  swagger setting response statusCode: 403 +0ms
  swagger:content setting response headers: {"Content-Type":"application/json"} +0ms
  swagger:content sending response body: {"message":"{\"message\":\"user password not valid in UK\",\"code\":\"server_error\",\"statusCode\":403}"} +0ms
  express-session saving +21ms
  express-session set-cookie sails.sid=s%3Ar1zCOa7eIy6hdJrGCHaQPDqx8BzY7Mv_.oMwf8hcPpFNKw9ytkKa6QBsyI8xEUZn7kH4f5LzURYU; Path=/; HttpOnly +1ms
  express:router matched get /person +14ms
  express:router matched get /person +1ms
  express-session saved +7ms
/Users/sganyo/temp/show-issue/node_modules/swagger-sails-hook/node_modules/swagger-node-runner/node_modules/bagpipes/node_modules/pipeworks/pipeworks.js:204
      throw err; // rethrow
```

So, it looks like there's another handler firing on the route after the response has been sent. I don't know enough about Sails to answer why it might have another handler on this, though. Thoughts?

**Comment by cgalibern** [comment]
@theganyo I found the reason: It is some of default blueprints config that are enabled by default:

-> this create automatically routes. 

I add `module.exports.blueprints = { action: false, rest: false, }` into config/blueprints.js
and it resolve the issue.

Perhaps some of  blueprints should be automatically disabled when we use swagger security handlers ?

**Comment by theganyo** [comment]
I'm glad you got it working! As for your question on Blueprints, I can't answer that. This type of interaction between the hook and the rest of the Sails system is probably best forwarded over to the Sails folks. I would have thought that sending a response would have been enough, but I'm guessing that Sails just isn't checking for that. Maybe it's a Sails bug or maybe it's intentional and there's another way the hook can tell the blueprints system it's been handled... @mikermcneil?

**Comment by cgalibern** [comment]
@theganyo, @mikermcneil Is there a reason to continue on next middlewares after sent response.end ?
shouldn't we stop there after sent 403 status code ?

https://github.com/theganyo/swagger-node-runner/blob/master/lib/connect_middleware.js#L86-L92

``` javascript
            if (context.output) {
              var body = translate(context.output, response.getHeader('content-type'));

              debugContent('sending response body: %s', body);
              response.end(body);
            }
            next();
```

**Comment by theganyo** [comment]
@cgalibern you're right. I shouldn't be calling next() after end(). I'm fixing that now.

**Comment by cgalibern** [comment]
Thanks!

**Comment by cgalibern** [comment]
I think we can now close this pul request.
Thanks

**Pull request closed without merging**
